language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt && scripts/build_and_local_install.sh
script:
  - py.test
  - fig --source tests/data/paragraph_input.txt --target test.xml
  - echo "Input Data:"
  - cat tests/data/paragraph_input.txt 
  - echo "Output Data:"
  - cat test.xml
